### ISSUE TITLE
rename controller

### ISSUE THREAD

**Issue by ugifractal** [tsaqib29/website#3]
rename file https://github.com/tsaqib29/website/blob/main/app/controllers/category_id_controller.rb
menjadi categories_controller.rb

**Comment by tsaqib29** [comment]
https://github.com/tsaqib29/website/commit/05c28c8e5a6a3ae7a2c8fe4143b691261ab9d43f#diff-2dc00eb2bf05a4c66ac3f613b5a981810b45881c19178dbbf9c830a08a7e9650
