### ISSUE TITLE
Judul buku tidak boleh kosong

### ISSUE THREAD

**Issue by ugifractal** [tsaqib29/website#4]
Klo judul buku di isi spasi saja, maka harus error dan tidak boleh di save.

video:
https://www.loom.com/share/da8f79ba75624d968572e4f4cae8bdc9

Tugas: Tambahkan validasi

Reference: 

https://guides.rubyonrails.org/active_record_validations.html
https://kpguerra96.medium.com/quick-guide-on-validations-in-rails-22fd6aca40e4

**Comment by ugifractal** [comment]
mana progress nya?

**Comment by tsaqib29** [comment]
susah

**Comment by ugifractal** [comment]
disini https://github.com/tsaqib29/website/blob/9f558e65c750a4ded645ee19d748ca460bd9fd97/app/models/book.rb#L8

tinggal tambah:

```ruby
validates :title, presence: true
```

**Comment by tsaqib29** [comment]
9f558e65c750a4ded645ee19d748ca460bd9fd97

**Comment by tsaqib29** [comment]
2f1cb3be3eab3fe8b6459ee8d6384988d5003977

**Comment by ugifractal** [comment]
hapus code ini sesuai komen di https://github.com/tsaqib29/website/commit/9f558e65c750a4ded645ee19d748ca460bd9fd97#r108408103

**Comment by ugifractal** [comment]
di https://github.com/tsaqib29/website/blob/2f1cb3be3eab3fe8b6459ee8d6384988d5003977/app/views/book/input.html.erb#L11

Ganti code
```
<input name="judul" required>
```

Menjadi

```erb
<%= text_field_tag(:judul) %>
```

Juga untuk pengarang dan ISBN

**Comment by tsaqib29** [comment]
8580bb3cbb8bea79f01f355bcdbe0fabc8da468e

**Comment by ugifractal** [comment]
hapus ```return``` di line 21 https://github.com/tsaqib29/website/blob/8580bb3cbb8bea79f01f355bcdbe0fabc8da468e/app/controllers/book_controller.rb#L21

Hapus ```flash``` di line 24
https://github.com/tsaqib29/website/blob/8580bb3cbb8bea79f01f355bcdbe0fabc8da468e/app/controllers/book_controller.rb#L24

Ganti ```redirect``` di line 25
https://github.com/tsaqib29/website/blob/8580bb3cbb8bea79f01f355bcdbe0fabc8da468e/app/controllers/book_controller.rb#L25

Menjadi
```render action: 'input'```
Supaya ketika gagal menyimpan, text yg telah diinput tidak menjadi kosong


Ganti
```
@data = Book.find_by(id: params[:id])
```

menjadi

```
@data = Book.new
```

https://github.com/tsaqib29/website/blob/8580bb3cbb8bea79f01f355bcdbe0fabc8da468e/app/controllers/book_controller.rb#L14

**Comment by tsaqib29** [comment]
70438a1cdd7ef14940fd7914ef752d5fa3d86f48

**Comment by ugifractal** [comment]
di https://github.com/tsaqib29/website/blob/70438a1cdd7ef14940fd7914ef752d5fa3d86f48/app/views/book/input.html.erb#L8

Tambahkan kode:
```erb
<% if @data.errors.size > 0 %>
   <% @data.errors.each do |error| %>
      <div>
         <%= error.full_message %>
      </div>
   <% end %>
<% end %>
```

**Comment by tsaqib29** [comment]
834bb490ec3fa7e217626eacca42104e044c5671

**Comment by ugifractal** [comment]
kelamaan commit nya

**Comment by ugifractal** [comment]
di https://github.com/tsaqib29/website/blob/834bb490ec3fa7e217626eacca42104e044c5671/app/controllers/book_controller.rb#L13

rename ```input``` jadi ```new``` sesuaikan perubahan nya baik dari controller,view dan routing nya.

**Comment by ugifractal** [comment]
https://github.com/tsaqib29/website/blob/834bb490ec3fa7e217626eacca42104e044c5671/app/controllers/book_controller.rb#L9

rename ```detail``` menjadi ```show```

**Comment by ugifractal** [comment]
https://github.com/tsaqib29/website/blob/834bb490ec3fa7e217626eacca42104e044c5671/app/controllers/book_controller.rb#L60

rename ```hapus``` menjadi ```destroy```

**Comment by ugifractal** [comment]
Untuk halaman edit berikan validasi error message juga ketika input tidak valid.

**Comment by ugifractal** [comment]
di book_controller, rename semua ```@data``` menjadi ```@book```
