### ISSUE TITLE
Buat sebuah field baru "availability_status"

### ISSUE THREAD

**Issue by ugifractal** [tsaqib29/website#5]
Buat sebuah field baru di database pada tabel "books" denga nama "availability_status" dengan tipe "string".

Gunakan "migration" untuk membuatnya:

"rails g migration add_availability_status_to_books"

tambahkan column dgn code

"add_column :books, :availability_status, :string, default: 'available' "

Jalankan migrasi dgn:

"rails db:migrate"

Cek tabel di sqlite dan upload screenshotnya sbg "comment" di github's issue.

**Comment by tsaqib29** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/113277896/231059181-5f2ec6bc-6971-44a3-aa59-28988c31a832.png)
